In [41]:
import pandas as pd
import numpy as np
import os
from os.path import join
import math

In [6]:
base_dir = os.path.dirname(os.path.realpath(__name__))
csv_files = [f for f in os.listdir(join(base_dir, 'Q2_data')) if f.endswith('.csv')]
csv_files

['201501-citibike-tripdata.csv',
 '201502-citibike-tripdata.csv',
 '201503-citibike-tripdata.csv',
 '201504-citibike-tripdata.csv',
 '201505-citibike-tripdata.csv',
 '201506-citibike-tripdata.csv',
 '201507-citibike-tripdata.csv',
 '201508-citibike-tripdata.csv',
 '201509-citibike-tripdata.csv',
 '201510-citibike-tripdata.csv',
 '201511-citibike-tripdata.csv',
 '201512-citibike-tripdata.csv']

In [8]:
dataframes = []
for csv_file in csv_files:
    dataframes.append(pd.read_csv(join('Q2_data', csv_file)))
    
len(dataframes)

12

In [24]:
data = pd.concat(dataframes)

In [10]:
data.shape

(9937969, 15)

In [11]:
list(data.columns.values)

['tripduration',
 'starttime',
 'stoptime',
 'start station id',
 'start station name',
 'start station latitude',
 'start station longitude',
 'end station id',
 'end station name',
 'end station latitude',
 'end station longitude',
 'bikeid',
 'usertype',
 'birth year',
 'gender']

Q1: What is the median trip duration, in seconds?

In [12]:
# ANSWER:Q1
np.median(data['tripduration'])

629.0

Q2: What fraction of rides start and end at the same station?

In [35]:
# Answer:
same_station = (data['start station id'] == data['end station id'])
print sum(same_station)

222197

In [36]:
fraction = float(sum(same_station)) / len(same_station)
fraction

0.022358391337304433

In [20]:
same_station2 = (data['start station name'] == data['end station name'])
print sum(same_station2)

222197

In [21]:
same_station3 = (data['start station latitude'] == data['end station latitude'])
print sum(same_station3)

222197

In [22]:
same_station4 = (data['start station longitude'] == data['end station longitude'])
print sum(same_station4)

222197

In [26]:
df_bike_station_start = data[['bikeid', 'start station id']]
df_bike_station_start.shape

(9937969, 2)

In [27]:
df_bike_station_end = data[['bikeid', 'end station id']]
df_bike_station_end.shape

(9937969, 2)

What is the standard deviation of the number of stations visited by a bike?

In [48]:
df_bike_station_start.columns=['bike', 'station id']
df_bike_station_end.columns=['bike', 'station id']
df_bike_station = pd.concat([df_bike_station_start, df_bike_station_end])
df_bike_station_groupby = df_bike_station.groupby("bike").agg({"station id": pd.Series.nunique})
# print df_bike_station_groupby
print np.std(df_bike_station_groupby['station id'])

54.5418965359

In [49]:
df_not_same_station = data[same_station == False]

What is the average length, in kilometers, of a trip?

In [44]:
lat1 = np.radians(df_not_same_station['start station latitude'])
lon1 = np.radians(df_not_same_station['start station longitude'])
lat2 = np.radians(df_not_same_station['end station latitude'])
lon2 = np.radians(df_not_same_station['end station longitude'])
R = 6373
dlon = lon2 - lon1
dlat = lat2 - lat1
a = (np.sin(dlat/2))**2 + np.cos(lat1) * np.cos(lat2) * (np.sin(dlon/2))**2 
c = 2 * np.arctan2( np.sqrt(a), np.sqrt(1-a) ) 
df_not_same_station['trip length'] = R * c
df_not_same_station

/Users/tamirlan/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,trip length
0,1346,1/1/2015 0:01,1/1/2015 0:24,455,1 Ave & E 44 St,40.750020,-73.969053,265,Stanton St & Chrystie St,40.722293,-73.991475,18660,Subscriber,1960.0,2,3.616955
1,363,1/1/2015 0:02,1/1/2015 0:08,434,9 Ave & W 18 St,40.743174,-74.003664,482,W 15 St & 7 Ave,40.739355,-73.999318,16085,Subscriber,1963.0,1,0.560921
2,346,1/1/2015 0:04,1/1/2015 0:10,491,E 24 St & Park Ave S,40.740964,-73.986022,505,6 Ave & W 33 St,40.749013,-73.988484,20845,Subscriber,1974.0,1,0.919008
3,182,1/1/2015 0:04,1/1/2015 0:07,384,Fulton St & Waverly Ave,40.683178,-73.965964,399,Lafayette Ave & St James Pl,40.688515,-73.964763,19610,Subscriber,1969.0,1,0.602242
4,969,1/1/2015 0:05,1/1/2015 0:21,474,5 Ave & E 29 St,40.745168,-73.986831,432,E 7 St & Avenue A,40.726218,-73.983799,20197,Subscriber,1977.0,1,2.123222
5,496,1/1/2015 0:07,1/1/2015 0:15,512,W 29 St & 9 Ave,40.750073,-73.998393,383,Greenwich Ave & Charles St,40.735238,-74.000271,20788,Subscriber,1969.0,2,1.657635
6,152,1/1/2015 0:07,1/1/2015 0:09,498,Broadway & W 32 St,40.748549,-73.988084,474,5 Ave & E 29 St,40.745168,-73.986831,19006,Subscriber,1972.0,1,0.390610
7,1183,1/1/2015 0:08,1/1/2015 0:28,405,Washington St & Gansevoort St,40.739323,-74.008119,174,E 25 St & 1 Ave,40.738177,-73.977387,17640,Subscriber,1985.0,2,2.593204
8,846,1/1/2015 0:09,1/1/2015 0:23,450,W 49 St & 8 Ave,40.762272,-73.987882,488,W 39 St & 9 Ave,40.756458,-73.993722,15691,Subscriber,1991.0,1,0.812582
9,576,1/1/2015 0:10,1/1/2015 0:20,160,E 37 St & Lexington Ave,40.748238,-73.978311,174,E 25 St & 1 Ave,40.738177,-73.977387,17837,Subscriber,1991.0,1,1.121847
10,540,1/1/2015 0:10,1/1/2015 0:19,291,Madison St & Montgomery St,40.713126,-73.984844,151,Cleveland Pl & Spring St,40.721816,-73.997203,16947,Subscriber,1979.0,1,1.421221
11,419,1/1/2015 0:11,1/1/2015 0:18,517,Pershing Square South,40.751581,-73.977910,540,Lexington Ave & E 26 St,40.741473,-73.983209,14807,Subscriber,1980.0,1,1.209763
12,751,1/1/2015 0:13,1/1/2015 0:25,290,2 Ave & E 58 St,40.760203,-73.964785,507,E 25 St & 2 Ave,40.739126,-73.979738,16702,Subscriber,1987.0,1,2.661496
13,332,1/1/2015 0:13,1/1/2015 0:18,361,Allen St & Hester St,40.716059,-73.991908,438,St Marks Pl & 1 Ave,40.727791,-73.985649,17342,Subscriber,1988.0,1,1.407615
14,1099,1/1/2015 0:14,1/1/2015 0:32,317,E 6 St & Avenue B,40.724537,-73.981854,2012,E 27 St & 1 Ave,40.739445,-73.976806,19909,Subscriber,1983.0,1,1.711899
15,649,1/1/2015 0:14,1/1/2015 0:25,488,W 39 St & 9 Ave,40.756458,-73.993722,434,9 Ave & W 18 St,40.743174,-74.003664,19584,Subscriber,1979.0,1,1.698532
16,614,1/1/2015 0:14,1/1/2015 0:24,285,Broadway & E 14 St,40.734546,-73.990741,312,Allen St & E Houston St,40.722055,-73.989111,19202,Subscriber,1959.0,1,1.396116
17,1196,1/1/2015 0:16,1/1/2015 0:36,466,W 25 St & 6 Ave,40.743954,-73.991449,454,E 51 St & 1 Ave,40.754557,-73.965930,20683,Subscriber,1971.0,1,2.452542
18,1426,1/1/2015 0:17,1/1/2015 0:40,360,William St & Pine St,40.707179,-74.008873,391,Clark St & Henry St,40.697601,-73.993446,21554,Subscriber,1977.0,1,1.681481
19,1262,1/1/2015 0:18,1/1/2015 0:39,485,W 37 St & 5 Ave,40.750380,-73.983390,251,Mott St & Prince St,40.723180,-73.994800,16894,Subscriber,1980.0,1,3.174664
20,707,1/1/2015 0:18,1/1/2015 0:30,449,W 52 St & 9 Ave,40.764618,-73.987895,509,9 Ave & W 22 St,40.745497,-74.001971,14598,Subscriber,1972.0,1,2.435193
21,307,1/1/2015 0:18,1/1/2015 0:23,474,5 Ave & E 29 St,40.745168,-73.986831,476,E 31 St & 3 Ave,40.743943,-73.979661,18834,Subscriber,1962.0,1,0.619390
22,1053,1/1/2015 0:19,1/1/2015 0:37,164,E 47 St & 2 Ave,40.753231,-73.970325,523,W 38 St & 8 Ave,40.754666,-73.991382,15617,Subscriber,1987.0,1,1.781348
23,446,1/1/2015 0:20,1/1/2015 0:27,522,E 51 St & Lexington Ave,40.757148,-73.972078,518,E 39 St & 2 Ave,40.747804,-73.973442,15812,Subscriber,1988.0,1,1.045646
24,1251,1/1/2015 0:21,1/1/2015 0:41,217,Old Fulton St,40.702772,-73.993836,313,Washington Ave & Park Ave,40.696102,-73.967510,19780,Customer,NaN,0,2.340653
25,797,1/1/2015 0:21,1/1/2015 0:35,513,W 56 St & 10 Ave,40.768254,-73.988639,488,W 39 St & 9 Ave,40.756458,-73.993722,16761,Subscriber,1969.0,1,1.380163
26,503,1/1/2015 0:21,1/1/2015 0:30,243,Fulton St & Rockwell Pl,40.688226,-73.979382,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,14570,Customer,NaN,0,0.837789
27,1639,1/1/2015 0:22,1/1/2015 0:49,382,University Pl & E 14 St,40.734927,-73.992005,352,W 56 St & 6 Ave,40.763406,-73.977225,18320,Subscriber,1996.0,2,3.403779
28,1175,1/1/2015 0:22,1/1/2015 0:42,217,Old Fulton St,40.702772,-73.993836,313,Washington Ave & Park Ave,40.696102,-73.967510,16610,Customer,NaN,0,2.340653
29,470,1/1/2015 0:22,1/1/2015 0:30,243,Fulton St & Rockwell Pl,40.688226,-73.979382,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,20804,Subscriber,1986.0,1,0.837789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804095,774,12/31/2015 18:50:41,12/31/2015 19:03:36,3238,E 80 St & 2 Ave,40.773914,-73.954395,3177,W 84 St & Broadway,40.786795,-73.977112,16964,Subscriber,1975.0,1,2.390292
804096,926,12/31/2015 21:13:54,12/31/2015 21:29:21,3238,E 80 St & 2 Ave,40.773914,-73.954395,3140,1 Ave & E 78 St,40.771404,-73.953517,22435,Subscriber,1976.0,1,0.288795
804097,279,12/24/2015 17:08:10,12/24/2015 17:12:49,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,344,Monroe St & Bedford Ave,40.685144,-73.953809,19527,Subscriber,1988.0,1,0.777777
804098,249,12/26/2015 17:56:26,12/26/2015 18:00:36,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,344,Monroe St & Bedford Ave,40.685144,-73.953809,22679,Subscriber,1977.0,2,0.777777
804099,1835,12/28/2015 08:13:00,12/28/2015 08:43:36,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,309,Murray St & West St,40.714979,-74.013012,23200,Subscriber,1977.0,1,6.590435
804100,310,12/28/2015 14:36:14,12/28/2015 14:41:24,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,3056,Kosciuszko St & Nostrand Ave,40.690725,-73.951335,19615,Subscriber,1977.0,2,0.752821
804101,331,12/28/2015 20:08:29,12/28/2015 20:14:00,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,3057,Kosciuszko St & Tompkins Ave,40.691283,-73.945242,17518,Subscriber,1986.0,1,0.566885
804102,479,12/29/2015 13:49:38,12/29/2015 13:57:38,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,437,Macon St & Nostrand Ave,40.680983,-73.950048,17562,Subscriber,1967.0,1,0.735533
804103,1833,12/30/2015 08:42:55,12/30/2015 09:13:29,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,309,Murray St & West St,40.714979,-74.013012,23868,Subscriber,1977.0,1,6.590435
804104,729,12/30/2015 09:05:03,12/30/2015 09:17:12,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,3065,Union Ave & Wallabout St,40.700295,-73.950323,18719,Subscriber,1979.0,2,1.637770
804105,206,12/30/2015 12:30:16,12/30/2015 12:33:42,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,3055,Greene Ave & Nostrand Ave,40.688334,-73.950916,18978,Subscriber,1986.0,1,0.575818
804106,237,12/30/2015 21:10:34,12/30/2015 21:14:32,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,3052,Lewis Ave & Madison St,40.686312,-73.935775,22785,Subscriber,1982.0,1,0.752367
804107,200,12/31/2015 08:09:56,12/31/2015 08:13:17,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,437,Macon St & Nostrand Ave,40.680983,-73.950048,23224,Subscriber,1988.0,1,0.735533
804108,2069,12/31/2015 08:56:46,12/31/2015 09:31:15,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,309,Murray St & West St,40.714979,-74.013012,23778,Subscriber,1977.0,1,6.590435
804109,1255,12/31/2015 15:56:35,12/31/2015 16:17:30,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,3095,Graham Ave & Herbert St,40.719293,-73.945004,22814,Customer,NaN,0,3.680689
804110,393,12/30/2015 15:24:41,12/30/2015 15:31:14,3242,Schermerhorn St & Court St,40.691029,-73.991834,391,Clark St & Henry St,40.697601,-73.993446,16574,Subscriber,1950.0,2,0.743537
804111,298,12/30/2015 16:01:14,12/30/2015 16:06:12,3242,Schermerhorn St & Court St,40.691029,-73.991834,406,Hicks St & Montague St,40.695128,-73.995951,16794,Subscriber,1956.0,1,0.573105
804112,270,12/30/2015 18:11:21,12/30/2015 18:15:52,3242,Schermerhorn St & Court St,40.691029,-73.991834,406,Hicks St & Montague St,40.695128,-73.995951,24246,Subscriber,1969.0,1,0.573105
804113,278,12/30/2015 22:30:17,12/30/2015 22:34:56,3242,Schermerhorn St & Court St,40.691029,-73.991834,323,Lawrence St & Willoughby St,40.692362,-73.986317,17440,Subscriber,1956.0,1,0.488261
804114,1155,12/31/2015 11:48:49,12/31/2015 12:08:05,3242,Schermerhorn St & Court St,40.691029,-73.991834,323,Lawrence St & Willoughby St,40.692362,-73.986317,23239,Subscriber,1966.0,2,0.488261
804115,498,12/31/2015 12:00:05,12/31/2015 12:08:23,3242,Schermerhorn St & Court St,40.691029,-73.991834,3222,Hanson Pl & St Felix St,40.685160,-73.977114,15594,Subscriber,1990.0,2,1.402716
804116,313,12/31/2015 13:44:49,12/31/2015 13:50:03,3242,Schermerhorn St & Court St,40.691029,-73.991834,391,Clark St & Henry St,40.697601,-73.993446,23510,Subscriber,1982.0,1,0.743537
804117,531,12/31/2015 15:05:11,12/31/2015 15:14:02,3242,Schermerhorn St & Court St,40.691029,-73.991834,467,Dean St & 4 Ave,40.683125,-73.978951,23901,Subscriber,1979.0,1,1.397696
804118,1483,12/31/2015 15:50:37,12/31/2015 16:15:20,3242,Schermerhorn St & Court St,40.691029,-73.991834,412,Forsyth St & Canal St,40.715816,-73.994224,23410,Customer,NaN,0,2.764326
804119,1463,12/31/2015 15:50:52,12/31/2015 16:15:15,3242,Schermerhorn St & Court St,40.691029,-73.991834,412,Forsyth St & Canal St,40.715816,-73.994224,20212,Customer,NaN,0,2.764326
804120,509,12/31/2015 16:50:17,12/31/2015 16:58:46,3242,Schermerhorn St & Court St,40.691029,-73.991834,261,Johnson St & Gold St,40.694749,-73.983625,22282,Subscriber,1957.0,1,0.806516
804121,591,12/31/2015 17:17:52,12/31/2015 17:27:43,3242,Schermerhorn St & Court St,40.691029,-73.991834,258,DeKalb Ave & Vanderbilt Ave,40.689407,-73.968855,22366,Subscriber,1978.0,1,1.946419
804122,197,12/31/2015 17:56:22,12/31/2015 17:59:39,3242,Schermerhorn St & Court St,40.691029,-73.991834,157,Henry St & Atlantic Ave,40.690893,-73.996123,20663,Subscriber,1959.0,1,0.362120
804123,372,12/31/2015 21:20:38,12/31/2015 21:26:50,3242,Schermerhorn St & Court St,40.691029,-73.991834,467,Dean St & 4 Ave,40.683125,-73.978951,19782,Subscriber,1987.0,1,1.397696
804124,395,12/31/2015 21:49:19,12/31/2015 21:55:55,3242,Schermerhorn St & Court St,40.691029,-73.991834,418,Front St & Gold St,40.702240,-73.982578,23411,Subscriber,1968.0,1,1.471113

In [47]:
np.mean(df_not_same_station['trip length'])

1.7602049199104772

Calculate the average duration of trips for each month in the year. (Consider a trip to occur in the month in which it starts.) What is the difference, in seconds, between the longest and shortest average durations?

In [104]:
#data['month'] = pd.DatetimeIndex(data['starttime']).month
data['month'] = data['starttime'].apply(lambda x: str(x).split('/')[0])

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,month
0,1346,1/1/2015 0:01,1/1/2015 0:24,455,1 Ave & E 44 St,40.750020,-73.969053,265,Stanton St & Chrystie St,40.722293,-73.991475,18660,Subscriber,1960.0,2,1
1,363,1/1/2015 0:02,1/1/2015 0:08,434,9 Ave & W 18 St,40.743174,-74.003664,482,W 15 St & 7 Ave,40.739355,-73.999318,16085,Subscriber,1963.0,1,1
2,346,1/1/2015 0:04,1/1/2015 0:10,491,E 24 St & Park Ave S,40.740964,-73.986022,505,6 Ave & W 33 St,40.749013,-73.988484,20845,Subscriber,1974.0,1,1
3,182,1/1/2015 0:04,1/1/2015 0:07,384,Fulton St & Waverly Ave,40.683178,-73.965964,399,Lafayette Ave & St James Pl,40.688515,-73.964763,19610,Subscriber,1969.0,1,1
4,969,1/1/2015 0:05,1/1/2015 0:21,474,5 Ave & E 29 St,40.745168,-73.986831,432,E 7 St & Avenue A,40.726218,-73.983799,20197,Subscriber,1977.0,1,1
5,496,1/1/2015 0:07,1/1/2015 0:15,512,W 29 St & 9 Ave,40.750073,-73.998393,383,Greenwich Ave & Charles St,40.735238,-74.000271,20788,Subscriber,1969.0,2,1
6,152,1/1/2015 0:07,1/1/2015 0:09,498,Broadway & W 32 St,40.748549,-73.988084,474,5 Ave & E 29 St,40.745168,-73.986831,19006,Subscriber,1972.0,1,1
7,1183,1/1/2015 0:08,1/1/2015 0:28,405,Washington St & Gansevoort St,40.739323,-74.008119,174,E 25 St & 1 Ave,40.738177,-73.977387,17640,Subscriber,1985.0,2,1
8,846,1/1/2015 0:09,1/1/2015 0:23,450,W 49 St & 8 Ave,40.762272,-73.987882,488,W 39 St & 9 Ave,40.756458,-73.993722,15691,Subscriber,1991.0,1,1
9,576,1/1/2015 0:10,1/1/2015 0:20,160,E 37 St & Lexington Ave,40.748238,-73.978311,174,E 25 St & 1 Ave,40.738177,-73.977387,17837,Subscriber,1991.0,1,1
10,540,1/1/2015 0:10,1/1/2015 0:19,291,Madison St & Montgomery St,40.713126,-73.984844,151,Cleveland Pl & Spring St,40.721816,-73.997203,16947,Subscriber,1979.0,1,1
11,419,1/1/2015 0:11,1/1/2015 0:18,517,Pershing Square South,40.751581,-73.977910,540,Lexington Ave & E 26 St,40.741473,-73.983209,14807,Subscriber,1980.0,1,1
12,751,1/1/2015 0:13,1/1/2015 0:25,290,2 Ave & E 58 St,40.760203,-73.964785,507,E 25 St & 2 Ave,40.739126,-73.979738,16702,Subscriber,1987.0,1,1
13,332,1/1/2015 0:13,1/1/2015 0:18,361,Allen St & Hester St,40.716059,-73.991908,438,St Marks Pl & 1 Ave,40.727791,-73.985649,17342,Subscriber,1988.0,1,1
14,1099,1/1/2015 0:14,1/1/2015 0:32,317,E 6 St & Avenue B,40.724537,-73.981854,2012,E 27 St & 1 Ave,40.739445,-73.976806,19909,Subscriber,1983.0,1,1
15,649,1/1/2015 0:14,1/1/2015 0:25,488,W 39 St & 9 Ave,40.756458,-73.993722,434,9 Ave & W 18 St,40.743174,-74.003664,19584,Subscriber,1979.0,1,1
16,614,1/1/2015 0:14,1/1/2015 0:24,285,Broadway & E 14 St,40.734546,-73.990741,312,Allen St & E Houston St,40.722055,-73.989111,19202,Subscriber,1959.0,1,1
17,1196,1/1/2015 0:16,1/1/2015 0:36,466,W 25 St & 6 Ave,40.743954,-73.991449,454,E 51 St & 1 Ave,40.754557,-73.965930,20683,Subscriber,1971.0,1,1
18,1426,1/1/2015 0:17,1/1/2015 0:40,360,William St & Pine St,40.707179,-74.008873,391,Clark St & Henry St,40.697601,-73.993446,21554,Subscriber,1977.0,1,1
19,1262,1/1/2015 0:18,1/1/2015 0:39,485,W 37 St & 5 Ave,40.750380,-73.983390,251,Mott St & Prince St,40.723180,-73.994800,16894,Subscriber,1980.0,1,1
20,707,1/1/2015 0:18,1/1/2015 0:30,449,W 52 St & 9 Ave,40.764618,-73.987895,509,9 Ave & W 22 St,40.745497,-74.001971,14598,Subscriber,1972.0,1,1
21,307,1/1/2015 0:18,1/1/2015 0:23,474,5 Ave & E 29 St,40.745168,-73.986831,476,E 31 St & 3 Ave,40.743943,-73.979661,18834,Subscriber,1962.0,1,1
22,1053,1/1/2015 0:19,1/1/2015 0:37,164,E 47 St & 2 Ave,40.753231,-73.970325,523,W 38 St & 8 Ave,40.754666,-73.991382,15617,Subscriber,1987.0,1,1
23,446,1/1/2015 0:20,1/1/2015 0:27,522,E 51 St & Lexington Ave,40.757148,-73.972078,518,E 39 St & 2 Ave,40.747804,-73.973442,15812,Subscriber,1988.0,1,1
24,1251,1/1/2015 0:21,1/1/2015 0:41,217,Old Fulton St,40.702772,-73.993836,313,Washington Ave & Park Ave,40.696102,-73.967510,19780,Customer,NaN,0,1
25,797,1/1/2015 0:21,1/1/2015 0:35,513,W 56 St & 10 Ave,40.768254,-73.988639,488,W 39 St & 9 Ave,40.756458,-73.993722,16761,Subscriber,1969.0,1,1
26,503,1/1/2015 0:21,1/1/2015 0:30,243,Fulton St & Rockwell Pl,40.688226,-73.979382,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,14570,Customer,NaN,0,1
27,1639,1/1/2015 0:22,1/1/2015 0:49,382,University Pl & E 14 St,40.734927,-73.992005,352,W 56 St & 6 Ave,40.763406,-73.977225,18320,Subscriber,1996.0,2,1
28,1175,1/1/2015 0:22,1/1/2015 0:42,217,Old Fulton St,40.702772,-73.993836,313,Washington Ave & Park Ave,40.696102,-73.967510,16610,Customer,NaN,0,1
29,470,1/1/2015 0:22,1/1/2015 0:30,243,Fulton St & Rockwell Pl,40.688226,-73.979382,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,20804,Subscriber,1986.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804095,774,12/31/2015 18:50:41,12/31/2015 19:03:36,3238,E 80 St & 2 Ave,40.773914,-73.954395,3177,W 84 St & Broadway,40.786795,-73.977112,16964,Subscriber,1975.0,1,12
804096,926,12/31/2015 21:13:54,12/31/2015 21:29:21,3238,E 80 St & 2 Ave,40.773914,-73.954395,3140,1 Ave & E 78 St,40.771404,-73.953517,22435,Subscriber,1976.0,1,12
804097,279,12/24/2015 17:08:10,12/24/2015 17:12:49,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,344,Monroe St & Bedford Ave,40.685144,-73.953809,19527,Subscriber,1988.0,1,12
804098,249,12/26/2015 17:56:26,12/26/2015 18:00:36,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,344,Monroe St & Bedford Ave,40.685144,-73.953809,22679,Subscriber,1977.0,2,12
804099,1835,12/28/2015 08:13:00,12/28/2015 08:43:36,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,309,Murray St & West St,40.714979,-74.013012,23200,Subscriber,1977.0,1,12
804100,310,12/28/2015 14:36:14,12/28/2015 14:41:24,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,3056,Kosciuszko St & Nostrand Ave,40.690725,-73.951335,19615,Subscriber,1977.0,2,12
804101,331,12/28/2015 20:08:29,12/28/2015 20:14:00,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,3057,Kosciuszko St & Tompkins Ave,40.691283,-73.945242,17518,Subscriber,1986.0,1,12
804102,479,12/29/2015 13:49:38,12/29/2015 13:57:38,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,437,Macon St & Nostrand Ave,40.680983,-73.950048,17562,Subscriber,1967.0,1,12
804103,1833,12/30/2015 08:42:55,12/30/2015 09:13:29,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,309,Murray St & West St,40.714979,-74.013012,23868,Subscriber,1977.0,1,12
804104,729,12/30/2015 09:05:03,12/30/2015 09:17:12,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,3065,Union Ave & Wallabout St,40.700295,-73.950323,18719,Subscriber,1979.0,2,12
804105,206,12/30/2015 12:30:16,12/30/2015 12:33:42,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,3055,Greene Ave & Nostrand Ave,40.688334,-73.950916,18978,Subscriber,1986.0,1,12
804106,237,12/30/2015 21:10:34,12/30/2015 21:14:32,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,3052,Lewis Ave & Madison St,40.686312,-73.935775,22785,Subscriber,1982.0,1,12
804107,200,12/31/2015 08:09:56,12/31/2015 08:13:17,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,437,Macon St & Nostrand Ave,40.680983,-73.950048,23224,Subscriber,1988.0,1,12
804108,2069,12/31/2015 08:56:46,12/31/2015 09:31:15,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,309,Murray St & West St,40.714979,-74.013012,23778,Subscriber,1977.0,1,12
804109,1255,12/31/2015 15:56:35,12/31/2015 16:17:30,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,3095,Graham Ave & Herbert St,40.719293,-73.945004,22814,Customer,NaN,0,12
804110,393,12/30/2015 15:24:41,12/30/2015 15:31:14,3242,Schermerhorn St & Court St,40.691029,-73.991834,391,Clark St & Henry St,40.697601,-73.993446,16574,Subscriber,1950.0,2,12
804111,298,12/30/2015 16:01:14,12/30/2015 16:06:12,3242,Schermerhorn St & Court St,40.691029,-73.991834,406,Hicks St & Montague St,40.695128,-73.995951,16794,Subscriber,1956.0,1,12
804112,270,12/30/2015 18:11:21,12/30/2015 18:15:52,3242,Schermerhorn St & Court St,40.691029,-73.991834,406,Hicks St & Montague St,40.695128,-73.995951,24246,Subscriber,1969.0,1,12
804113,278,12/30/2015 22:30:17,12/30/2015 22:34:56,3242,Schermerhorn St & Court St,40.691029,-73.991834,323,Lawrence St & Willoughby St,40.692362,-73.986317,17440,Subscriber,1956.0,1,12
804114,1155,12/31/2015 11:48:49,12/31/2015 12:08:05,3242,Schermerhorn St & Court St,40.691029,-73.991834,323,Lawrence St & Willoughby St,40.692362,-73.986317,23239,Subscriber,1966.0,2,12
804115,498,12/31/2015 12:00:05,12/31/2015 12:08:23,3242,Schermerhorn St & Court St,40.691029,-73.991834,3222,Hanson Pl & St Felix St,40.685160,-73.977114,15594,Subscriber,1990.0,2,12
804116,313,12/31/2015 13:44:49,12/31/2015 13:50:03,3242,Schermerhorn St & Court St,40.691029,-73.991834,391,Clark St & Henry St,40.697601,-73.993446,23510,Subscriber,1982.0,1,12
804117,531,12/31/2015 15:05:11,12/31/2015 15:14:02,3242,Schermerhorn St & Court St,40.691029,-73.991834,467,Dean St & 4 Ave,40.683125,-73.978951,23901,Subscriber,1979.0,1,12
804118,1483,12/31/2015 15:50:37,12/31/2015 16:15:20,3242,Schermerhorn St & Court St,40.691029,-73.991834,412,Forsyth St & Canal St,40.715816,-73.994224,23410,Customer,NaN,0,12
804119,1463,12/31/2015 15:50:52,12/31/2015 16:15:15,3242,Schermerhorn St & Court St,40.691029,-73.991834,412,Forsyth St & Canal St,40.715816,-73.994224,20212,Customer,NaN,0,12
804120,509,12/31/2015 16:50:17,12/31/2015 16:58:46,3242,Schermerhorn St & Court St,40.691029,-73.991834,261,Johnson St & Gold St,40.694749,-73.983625,22282,Subscriber,1957.0,1,12
804121,591,12/31/2015 17:17:52,12/31/2015 17:27:43,3242,Schermerhorn St & Court St,40.691029,-73.991834,258,DeKalb Ave & Vanderbilt Ave,40.689407,-73.968855,22366,Subscriber,1978.0,1,12
804122,197,12/31/2015 17:56:22,12/31/2015 17:59:39,3242,Schermerhorn St & Court St,40.691029,-73.991834,157,Henry St & Atlantic Ave,40.690893,-73.996123,20663,Subscriber,1959.0,1,12
804123,372,12/31/2015 21:20:38,12/31/2015 21:26:50,3242,Schermerhorn St & Court St,40.691029,-73.991834,467,Dean St & 4 Ave,40.683125,-73.978951,19782,Subscriber,1987.0,1,12
804124,395,12/31/2015 21:49:19,12/31/2015 21:55:55,3242,Schermerhorn St & Court St,40.691029,-73.991834,418,Front St & Gold St,40.702240,-73.982578,23411,Subscriber,1968.0,1,12

In [108]:
df = data.groupby("month").agg({"tripduration": np.mean})
print df
longest = max(df['tripduration'])
shortest = min(df['tripduration'])
print longest
print shortest
print longest - shortest

       tripduration
month
1        654.325583
10      1079.953503
11       972.018670
12       945.711619
2        649.383207
3        734.316673
4        929.884482
5       1000.233767
6        904.602783
7        967.670092
8       1017.478667
9       1050.849829
1079.9535032
649.383207231
430.57029597

Let us define the hourly usage fraction of a station to be the fraction of all rides starting at that station that leave during a specific hour. A station has surprising usage patterns if it has an hourly usage fraction for an hour significantly different from the corresponding hourly usage fraction of the system as a whole. What is the largest ratio of station hourly usage fraction to system hourly usage fraction (hence corresponding to the most "surprising" station-hour pair)?

In [115]:
# data['hour'] = pd.DatetimeIndex(data['starttime']).hour
data['hour'] = data['starttime'].apply(lambda x: str(x).split()[1].split(':')[0] if len(str(x).split()[1].split(':')[0])==2 else '0' + str(x).split()[1].split(':')[0])

In [117]:
slice_df2 = data.groupby("hour").agg({"tripduration": 'count'})
slice_df2.columns = ['system hourly fraction']
slice_df2['system hourly fraction'] = slice_df2['system hourly fraction'] / sum(slice_df2['system hourly fraction'])

In [119]:
sum(slice_df2['system hourly fraction'])

1.0

In [120]:
slice_df3 = slice_df.groupby(['hour', 'start station id']).agg({'tripduration': 'count'}).reset_index()
slice_df3.columns = ['hour', 'start station id', 'count']

In [122]:
slice_df4 = slice_df3.groupby('hour').agg({'count': 'count'})
# print slice_df2
slice_df2['count by station'] = slice_df4['count']
slice_df2['max by station'] = slice_df3.groupby('hour').agg({'count': max})
slice_df2['fraction max by station'] = slice_df2['max by station'] / slice_df2['count by station']
slice_df2['golden ration'] = slice_df2['fraction max by station'] / slice_df2['system hourly fraction']
print 'Largest Ratio:', max(slice_df2['golden ration'])

Largest Ratio: 1405.54872537

In [123]:
slice_df2

,system hourly fraction,count by station,max by station,fraction max by station,golden ration
hour,,,,,
00,0.009565,478,1349,2.822176,295.051337
01,0.005400,478,833,1.742678,322.724325
02,0.003147,466,543,1.165236,370.313701
03,0.001953,462,419,0.906926,464.372534
04,0.001808,451,423,0.937916,518.898713
05,0.005426,464,3539,7.627155,1405.548725
06,0.021524,478,12844,26.870293,1248.392446
07,0.044971,483,17481,36.192547,804.794586
08,0.080143,485,17812,36.725773,458.253987
09,0.064534,485,10201,21.032990,325.919989
10,0.044514,485,4754,9.802062,220.201155
11,0.046673,487,4739,9.731006,208.494086
12,0.054034,487,5537,11.369610,210.413972
13,0.056550,488,5727,11.735656,207.526754
14,0.058384,485,6010,12.391753,212.245102
15,0.061240,485,6022,12.416495,202.751792
16,0.071057,484,7062,14.590909,205.340987
17,0.097625,486,15056,30.979424,317.329611
18,0.093250,485,16558,34.140206,366.116238
19,0.065221,483,7824,16.198758,248.367315
20,0.043217,483,4958,10.265010,237.519860
21,0.030587,482,3600,7.468880,244.186909
22,0.023265,481,2803,5.827443,250.483104
23,0.015912,479,2224,4.643006,291.796373

There are two types of riders: "Customers" and "Subscribers." Customers buy a short-time pass which allows 30-minute rides. Subscribers buy yearly passes that allow 45-minute rides. What fraction of rides exceed their corresponding time limit?

In [132]:
exceed = (data['usertype'] == 'Subscriber') & (data['tripduration'] > 45*60) | (data['usertype'] == 'Customer') & (data['tripduration'] > 30*60)

0

In [133]:
float(sum(exceed)) / len(exceed)

0.038106780168060496

Most of the time, a bike will begin a trip at the same station where its previous trip ended. Sometimes a bike will be moved by the program, either for maintenance or to rebalance the distribution of bikes. What is the average number of times a bike is moved during this period, as detected by seeing if it starts at a different station than where the previous ride ended?

In [140]:
df0 = data.groupby(['bikeid', 'starttime', 'start station id', 'end station id']).count().reset_index()#.agg({"station id": pd.Series.nunique})

In [141]:
df0

,bikeid,starttime,start station id,end station id,tripduration,stoptime,start station name,start station latitude,start station longitude,end station name,end station latitude,end station longitude,usertype,birth year,gender,month,hour
0,14529,1/1/2015 12:28,326,497,1,1,1,1,1,1,1,1,1,1,1,1,1
1,14529,1/1/2015 13:11,497,515,1,1,1,1,1,1,1,1,1,1,1,1,1
2,14529,1/12/2015 10:22,479,512,1,1,1,1,1,1,1,1,1,1,1,1,1
3,14529,1/12/2015 14:08,512,489,1,1,1,1,1,1,1,1,1,1,1,1,1
4,14529,1/12/2015 15:01,489,515,1,1,1,1,1,1,1,1,1,1,1,1,1
5,14529,1/12/2015 15:55,515,434,1,1,1,1,1,1,1,1,1,1,1,1,1
6,14529,1/12/2015 16:50,434,357,1,1,1,1,1,1,1,1,1,1,1,1,1
7,14529,1/12/2015 18:20,357,469,1,1,1,1,1,1,1,1,1,1,1,1,1
8,14529,1/12/2015 18:52,469,490,1,1,1,1,1,1,1,1,1,1,1,1,1
9,14529,1/12/2015 19:16,490,352,1,1,1,1,1,1,1,1,1,1,1,1,1
10,14529,1/12/2015 20:07,352,2022,1,1,1,1,1,1,1,1,1,1,1,1,1
11,14529,1/12/2015 20:24,2022,447,1,1,1,1,1,1,1,1,1,1,1,1,1
12,14529,1/12/2015 21:02,447,495,1,1,1,1,1,1,1,1,1,1,1,1,1
13,14529,1/12/2015 21:10,495,352,1,1,1,1,1,1,1,1,1,1,1,1,1
14,14529,1/12/2015 6:55,465,359,1,1,1,1,1,1,1,1,1,1,1,1,1
15,14529,1/12/2015 8:23,359,479,1,1,1,1,1,1,1,1,1,1,1,1,1
16,14529,1/13/2015 0:14,352,515,1,1,1,1,1,1,1,1,1,1,1,1,1
17,14529,1/13/2015 18:58,402,280,1,1,1,1,1,1,1,1,1,1,1,1,1
18,14529,1/13/2015 9:01,237,402,1,1,1,1,1,1,1,1,1,1,1,1,1
19,14529,1/14/2015 0:10,280,342,1,1,1,1,1,1,1,1,1,1,1,1,1
20,14529,1/14/2015 13:07,296,249,1,1,1,1,1,1,1,1,1,1,1,1,1
21,14529,1/14/2015 17:31,249,540,1,1,1,1,1,1,1,1,1,1,1,1,1
22,14529,1/14/2015 18:42,540,167,1,1,1,1,1,1,1,1,1,1,1,1,1
23,14529,1/14/2015 19:27,167,476,1,1,1,1,1,1,1,1,1,1,1,1,1
24,14529,1/14/2015 22:57,476,393,1,1,1,1,1,1,1,1,1,1,1,1,1
25,14529,1/14/2015 8:46,342,531,1,1,1,1,1,1,1,1,1,1,1,1,1
26,14529,1/14/2015 9:13,531,296,1,1,1,1,1,1,1,1,1,1,1,1,1
27,14529,1/15/2015 16:59,2010,368,1,1,1,1,1,1,1,1,1,1,1,1,1
28,14529,1/15/2015 17:09,368,466,1,1,1,1,1,1,1,1,1,1,1,1,1
29,14529,1/15/2015 17:22,466,463,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9937934,24769,12/18/2015 18:59:20,490,3129,1,1,1,1,1,1,1,1,1,1,1,1,1
9937935,24769,12/19/2015 01:34:39,3129,3124,1,1,1,1,1,1,1,1,1,1,1,1,1
9937936,24769,12/19/2015 09:31:58,3124,3104,1,1,1,1,1,1,1,1,1,1,1,1,1
9937937,24769,12/20/2015 17:20:47,3104,3112,1,1,1,1,1,1,1,1,1,1,1,1,1
9937938,24769,12/20/2015 17:40:33,3112,3103,1,1,1,1,1,1,1,1,1,1,1,1,1
9937939,24769,12/22/2015 01:09:47,3103,3104,1,1,1,1,1,1,1,1,1,1,1,1,1
9937940,24769,12/24/2015 15:51:11,3086,3089,1,1,1,1,1,1,1,1,1,1,1,1,1
9937941,24769,12/24/2015 23:31:11,3089,3108,1,1,1,1,1,1,1,1,1,1,1,1,1
9937942,24769,12/26/2015 08:52:14,3108,473,1,1,1,1,1,1,1,1,1,1,1,1,1
9937943,24769,12/28/2015 18:26:59,473,326,1,1,1,1,1,1,1,1,1,1,1,1,1
9937944,24769,12/28/2015 19:00:22,326,301,1,1,1,1,1,1,1,1,1,1,1,1,1
9937945,24769,12/29/2015 08:12:34,301,403,1,1,1,1,1,1,1,1,1,1,1,1,1
9937946,24769,12/29/2015 09:27:45,403,486,1,1,1,1,1,1,1,1,1,1,1,1,1
9937947,24769,12/29/2015 13:16:12,486,536,1,1,1,1,1,1,1,1,1,1,1,1,1
9937948,24769,12/29/2015 13:53:26,536,445,1,1,1,1,1,1,1,1,1,1,1,1,1
9937949,24769,12/29/2015 14:15:20,445,521,1,1,1,1,1,1,1,1,1,1,1,1,1
9937950,24769,12/29/2015 15:22:12,521,72,1,1,1,1,1,1,1,1,1,1,1,1,1
9937951,24769,12/29/2015 16:15:05,72,479,1,1,1,1,1,1,1,1,1,1,1,1,1
9937952,24769,12/29/2015 18:33:19,479,448,1,1,1,1,1,1,1,1,1,1,1,1,1
9937953,24769,12/29/2015 18:59:05,448,352,1,1,1,1,1,1,1,1,1,1,1,1,1
9937954,24769,12/29/2015 19:13:09,352,2021,1,1,1,1,1,1,1,1,1,1,1,1,1
9937955,24769,12/29/2015 20:19:45,2021,323,1,1,1,1,1,1,1,1,1,1,1,1,1
9937956,24769,12/29/2015 21:11:28,323,270,1,1,1,1,1,1,1,1,1,1,1,1,1
9937957,24769,12/30/2015 08:29:59,270,323,1,1,1,1,1,1,1,1,1,1,1,1,1
9937958,24769,12/30/2015 18:46:02,323,484,1,1,1,1,1,1,1,1,1,1,1,1,1
9937959,24769,12/30/2015 19:35:28,484,489,1,1,1,1,1,1,1,1,1,1,1,1,1
9937960,24769,12/30/2015 20:18:36,489,466,1,1,1,1,1,1,1,1,1,1,1,1,1
9937961,24769,12/30/2015 20:56:31,466,3178,1,1,1,1,1,1,1,1,1,1,1,1,1
9937962,24769,12/31/2015 09:16:17,3178,417,1,1,1,1,1,1,1,1,1,1,1,1,1
9937963,24769,12/31/2015 09:49:46,417,390,1,1,1,1,1,1,1,1,1,1,1,1,1

In [146]:
#dff = data.groupby(['bikeid', 'start station id', 'end station id', 'starttime']).reset_index()
dff = data.sort(['bikeid', 'starttime'])
dff

/Users/tamirlan/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,month,hour
1524,332,1/1/2015 12:28,1/1/2015 12:34,326,E 11 St & 1 Ave,40.729538,-73.984267,497,E 17 St & Broadway,40.737050,-73.990093,14529,Subscriber,1982.0,1,1,12
1793,829,1/1/2015 13:11,1/1/2015 13:24,497,E 17 St & Broadway,40.737050,-73.990093,515,W 43 St & 10 Ave,40.760094,-73.994618,14529,Subscriber,1991.0,1,1,13
94762,387,1/12/2015 10:22,1/12/2015 10:29,479,9 Ave & W 45 St,40.760193,-73.991255,512,W 29 St & 9 Ave,40.750073,-73.998393,14529,Subscriber,1985.0,1,1,10
95286,160,1/12/2015 14:08,1/12/2015 14:11,512,W 29 St & 9 Ave,40.750073,-73.998393,489,10 Ave & W 28 St,40.750664,-74.001768,14529,Subscriber,1971.0,1,1,14
95408,392,1/12/2015 15:01,1/12/2015 15:08,489,10 Ave & W 28 St,40.750664,-74.001768,515,W 43 St & 10 Ave,40.760094,-73.994618,14529,Subscriber,1969.0,1,1,15
95589,591,1/12/2015 15:55,1/12/2015 16:05,515,W 43 St & 10 Ave,40.760094,-73.994618,434,9 Ave & W 18 St,40.743174,-74.003664,14529,Subscriber,1979.0,1,1,15
95984,419,1/12/2015 16:50,1/12/2015 16:57,434,9 Ave & W 18 St,40.743174,-74.003664,357,E 11 St & Broadway,40.732618,-73.991580,14529,Subscriber,1984.0,1,1,16
97689,1060,1/12/2015 18:20,1/12/2015 18:37,357,E 11 St & Broadway,40.732618,-73.991580,469,Broadway & W 53 St,40.763441,-73.982681,14529,Subscriber,1984.0,1,1,18
98389,703,1/12/2015 18:52,1/12/2015 19:03,469,Broadway & W 53 St,40.763441,-73.982681,490,8 Ave & W 33 St,40.751551,-73.993934,14529,Subscriber,1959.0,1,1,18
98808,801,1/12/2015 19:16,1/12/2015 19:29,490,8 Ave & W 33 St,40.751551,-73.993934,352,W 56 St & 6 Ave,40.763406,-73.977225,14529,Subscriber,1983.0,1,1,19
99525,523,1/12/2015 20:07,1/12/2015 20:16,352,W 56 St & 6 Ave,40.763406,-73.977225,2022,E 59 St & Sutton Pl,40.758491,-73.959206,14529,Subscriber,1965.0,1,1,20
99723,827,1/12/2015 20:24,1/12/2015 20:38,2022,E 59 St & Sutton Pl,40.758491,-73.959206,447,8 Ave & W 52 St,40.763707,-73.985162,14529,Subscriber,1975.0,1,1,20
100076,311,1/12/2015 21:02,1/12/2015 21:07,447,8 Ave & W 52 St,40.763707,-73.985162,495,W 47 St & 10 Ave,40.762699,-73.993012,14529,Subscriber,1982.0,1,1,21
100139,569,1/12/2015 21:10,1/12/2015 21:19,495,W 47 St & 10 Ave,40.762699,-73.993012,352,W 56 St & 6 Ave,40.763406,-73.977225,14529,Subscriber,1968.0,1,1,21
92747,454,1/12/2015 6:55,1/12/2015 7:02,465,Broadway & W 41 St,40.755136,-73.986580,359,E 47 St & Park Ave,40.755103,-73.974987,14529,Subscriber,1964.0,1,1,06
93800,393,1/12/2015 8:23,1/12/2015 8:29,359,E 47 St & Park Ave,40.755103,-73.974987,479,9 Ave & W 45 St,40.760193,-73.991255,14529,Subscriber,1966.0,1,1,08
100806,768,1/13/2015 0:14,1/13/2015 0:26,352,W 56 St & 6 Ave,40.763406,-73.977225,515,W 43 St & 10 Ave,40.760094,-73.994618,14529,Subscriber,1978.0,1,1,00
111528,332,1/13/2015 18:58,1/13/2015 19:04,402,Broadway & E 22 St,40.740343,-73.989551,280,E 10 St & 5 Ave,40.733320,-73.995101,14529,Subscriber,1986.0,2,1,18
104101,432,1/13/2015 9:01,1/13/2015 9:08,237,E 11 St & 2 Ave,40.730473,-73.986724,402,Broadway & E 22 St,40.740343,-73.989551,14529,Subscriber,1980.0,1,1,09
113584,772,1/14/2015 0:10,1/14/2015 0:23,280,E 10 St & 5 Ave,40.733320,-73.995101,342,Columbia St & Rivington St,40.717400,-73.980166,14529,Subscriber,1963.0,1,1,00
119000,479,1/14/2015 13:07,1/14/2015 13:15,296,Division St & Bowery,40.714131,-73.997047,249,Harrison St & Hudson St,40.718710,-74.009001,14529,Subscriber,1969.0,1,1,13
122124,1392,1/14/2015 17:31,1/14/2015 17:54,249,Harrison St & Hudson St,40.718710,-74.009001,540,Lexington Ave & E 26 St,40.741473,-73.983209,14529,Subscriber,1963.0,1,1,17
123946,367,1/14/2015 18:42,1/14/2015 18:49,540,Lexington Ave & E 26 St,40.741473,-73.983209,167,E 39 St & 3 Ave,40.748901,-73.976049,14529,Subscriber,1948.0,1,1,18
124765,224,1/14/2015 19:27,1/14/2015 19:30,167,E 39 St & 3 Ave,40.748901,-73.976049,476,E 31 St & 3 Ave,40.743943,-73.979661,14529,Subscriber,1987.0,1,1,19
126488,1124,1/14/2015 22:57,1/14/2015 23:15,476,E 31 St & 3 Ave,40.743943,-73.979661,393,E 5 St & Avenue C,40.722992,-73.979955,14529,Subscriber,1955.0,1,1,22
116152,639,1/14/2015 8:46,1/14/2015 8:57,342,Columbia St & Rivington St,40.717400,-73.980166,531,Forsyth St & Broome St,40.718939,-73.992663,14529,Subscriber,1974.0,2,1,08
116791,256,1/14/2015 9:13,1/14/2015 9:17,531,Forsyth St & Broome St,40.718939,-73.992663,296,Division St & Bowery,40.714131,-73.997047,14529,Subscriber,1972.0,1,1,09
135607,436,1/15/2015 16:59,1/15/2015 17:06,2010,Grand St & Greene St,40.721655,-74.002347,368,Carmine St & 6 Ave,40.730386,-74.002150,14529,Subscriber,1983.0,1,1,16
135828,463,1/15/2015 17:09,1/15/2015 17:16,368,Carmine St & 6 Ave,40.730386,-74.002150,466,W 25 St & 6 Ave,40.743954,-73.991449,14529,Subscriber,1956.0,1,1,17
136135,593,1/15/2015 17:22,1/15/2015 17:32,466,W 25 St & 6 Ave,40.743954,-73.991449,463,9 Ave & W 16 St,40.742065,-74.004432,14529,Subscriber,1954.0,2,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507072,1244,12/18/2015 18:59:20,12/18/2015 19:20:05,490,8 Ave & W 33 St,40.751551,-73.993934,3129,Queens Plaza North & Crescent St,40.751102,-73.940737,24769,Subscriber,1977.0,1,12,18
720274,371,12/19/2015 01:34:39,12/19/2015 01:40:50,3129,Queens Plaza North & Crescent St,40.751102,-73.940737,3124,46 Ave & 5 St,40.747310,-73.954510,24769,Subscriber,1977.0,1,12,01
718518,742,12/19/2015 09:31:58,12/19/2015 09:44:20,3124,46 Ave & 5 St,40.747310,-73.954510,3104,Kent Ave & N 7 St,40.720577,-73.961502,24769,Subscriber,1989.0,1,12,09
708251,243,12/20/2015 17:20:47,12/20/2015 17:24:51,3104,Kent Ave & N 7 St,40.720577,-73.961502,3112,Milton St & Franklin St,40.729060,-73.957790,24769,Subscriber,1986.0,2,12,17
713382,326,12/20/2015 17:40:33,12/20/2015 17:45:59,3112,Milton St & Franklin St,40.729060,-73.957790,3103,N 11 St & Wythe Ave,40.721533,-73.957824,24769,Subscriber,1986.0,2,12,17
707192,104,12/22/2015 01:09:47,12/22/2015 01:11:32,3103,N 11 St & Wythe Ave,40.721533,-73.957824,3104,Kent Ave & N 7 St,40.720577,-73.961502,24769,Subscriber,1979.0,1,12,01
698115,156,12/24/2015 15:51:11,12/24/2015 15:53:47,3086,Graham Ave & Conselyea St,40.715143,-73.944507,3089,Leonard St & Meeker Ave,40.717318,-73.948202,24769,Subscriber,1979.0,1,12,15
699458,452,12/24/2015 23:31:11,12/24/2015 23:38:44,3089,Leonard St & Meeker Ave,40.717318,-73.948202,3108,Nassau Ave & Russell St,40.725570,-73.944340,24769,Subscriber,1987.0,1,12,23
711080,1177,12/26/2015 08:52:14,12/26/2015 09:11:52,3108,Nassau Ave & Russell St,40.725570,-73.944340,473,Rivington St & Chrystie St,40.721101,-73.991925,24769,Subscriber,1981.0,1,12,08
456846,407,12/28/2015 18:26:59,12/28/2015 18:33:46,473,Rivington St & Chrystie St,40.721101,-73.991925,326,E 11 St & 1 Ave,40.729538,-73.984267,24769,Subscriber,1981.0,2,12,18
196385,375,12/28/2015 19:00:22,12/28/2015 19:06:37,326,E 11 St & 1 Ave,40.729538,-73.984267,301,E 2 St & Avenue B,40.722174,-73.983688,24769,Subscriber,1979.0,2,12,19
157673,212,12/29/2015 08:12:34,12/29/2015 08:16:07,301,E 2 St & Avenue B,40.722174,-73.983688,403,E 2 St & 2 Ave,40.725029,-73.990697,24769,Subscriber,1990.0,1,12,08
323912,731,12/29/2015 09:27:45,12/29/2015 09:39:56,403,E 2 St & 2 Ave,40.725029,-73.990697,486,Broadway & W 29 St,40.746201,-73.988557,24769,Subscriber,1965.0,2,12,09
493929,425,12/29/2015 13:16:12,12/29/2015 13:23:18,486,Broadway & W 29 St,40.746201,-73.988557,536,1 Ave & E 30 St,40.741444,-73.975361,24769,Subscriber,1983.0,1,12,13
643767,567,12/29/2015 13:53:26,12/29/2015 14:02:53,536,1 Ave & E 30 St,40.741444,-73.975361,445,E 10 St & Avenue A,40.727408,-73.981420,24769,Subscriber,1982.0,1,12,13
391723,1164,12/29/2015 14:15:20,12/29/2015 14:34:44,445,E 10 St & Avenue A,40.727408,-73.981420,521,8 Ave & W 31 St,40.750967,-73.994442,24769,Subscriber,1995.0,1,12,14
608356,726,12/29/2015 15:22:12,12/29/2015 15:34:18,521,8 Ave & W 31 St,40.750967,-73.994442,72,W 52 St & 11 Ave,40.767272,-73.993929,24769,Subscriber,1972.0,1,12,15
1542,272,12/29/2015 16:15:05,12/29/2015 16:19:37,72,W 52 St & 11 Ave,40.767272,-73.993929,479,9 Ave & W 45 St,40.760193,-73.991255,24769,Subscriber,1973.0,1,12,16
475581,369,12/29/2015 18:33:19,12/29/2015 18:39:29,479,9 Ave & W 45 St,40.760193,-73.991255,448,W 37 St & 10 Ave,40.756604,-73.997901,24769,Subscriber,1982.0,2,12,18
400966,719,12/29/2015 18:59:05,12/29/2015 19:11:05,448,W 37 St & 10 Ave,40.756604,-73.997901,352,W 56 St & 6 Ave,40.763406,-73.977225,24769,Subscriber,1981.0,2,12,18
239494,983,12/29/2015 19:13:09,12/29/2015 19:29:32,352,W 56 St & 6 Ave,40.763406,-73.977225,2021,W 45 St & 8 Ave,40.759291,-73.988597,24769,Subscriber,1983.0,1,12,19
680630,2177,12/29/2015 20:19:45,12/29/2015 20:56:02,2021,W 45 St & 8 Ave,40.759291,-73.988597,323,Lawrence St & Willoughby St,40.692362,-73.986317,24769,Subscriber,1986.0,1,12,20
190599,457,12/29/2015 21:11:28,12/29/2015 21:19:05,323,Lawrence St & Willoughby St,40.692362,-73.986317,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,24769,Subscriber,1973.0,1,12,21
115860,342,12/30/2015 08:29:59,12/30/2015 08:35:42,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,323,Lawrence St & Willoughby St,40.692362,-73.986317,24769,Subscriber,1973.0,1,12,08
190625,2871,12/30/2015 18:46:02,12/30/2015 19:33:53,323,Lawrence St & Willoughby St,40.692362,-73.986317,484,W 44 St & 5 Ave,40.755003,-73.980144,24769,Subscriber,1954.0,1,12,18
488434,849,12/30/2015 19:35:28,12/30/2015 19:49:37,484,W 44 St & 5 Ave,40.755003,-73.980144,489,10 Ave & W 28 St,40.750664,-74.001768,24769,Subscriber,1979.0,1,12,19
503400,424,12/30/2015 20:18:36,12/30/2015 20:25:40,489,10 Ave & W 28 St,40.750664,-74.001768,466,W 25 St & 6 Ave,40.743954,-73.991449,24769,Subscriber,1990.0,1,12,20
441827,2241,12/30/2015 20:56:31,12/30/2015 21:33:52,466,W 25 St & 6 Ave,40.743954,-73.991449,3178,Riverside Dr & W 78 St,40.784145,-73.983625,24769,Subscriber,1964.0,1,12,20
782171,1828,12/31/2015 09:16:17,12/31/2015 09:46:46,3178,Riverside Dr & W 78 St,40.784145,-73.983625,417,Barclay St & Church St,40.712912,-74.010202,24769,Subscriber,1976.0,2,12,09
341063,854,12/31/2015 09:49:46,12/31/2015 10:04:00,417,Barclay St & Church St,40.712912,-74.010202,390,Duffield St & Willoughby St,40.692216,-73.984284,24769,Subscriber,1981.0,1,12,09

In [147]:
dff['end station id'] = dff['end station id'].shift(1)

In [154]:
good = (dff['start station id'] == dff['end station id'])
goodsum = sum(good)

In [150]:
unique = len(dff.bikeid.unique())
unique

8477

In [156]:
all = len(good)
all

9937969

In [161]:
float(goodsum + unique)/unique

1038.73032912587